language: c 
sudo: false

env:
  global:
    - PATH=$HOME/miniconda/bin:$PATH
  matrix:
    - python=2.7  CONDA_PY=27  CONDA_NPY=17
    - python=3.4  CONDA_PY=34  CONDA_NPY=18
    - python=3.4  CONDA_PY=34  CONDA_NPY=19
    - python=3.5  CONDA_PY=35  CONDA_NPY=19

before_install:
- tools/ci/travis/install_miniconda.sh
- conda install conda-build -qy
- conda list

script:
- conda build tools/conda-recipe

after_success:
- pip install coveralls
- coveralls

