language: c
sudo: false

env:
  global:
    - PATH=$HOME/miniconda/bin:$PATH
  matrix:
    - python=2.7  CONDA_PY=27  CONDA_NPY=17
    - python=3.5  CONDA_PY=35  CONDA_NPY=19
    - python=3.6  CONDA_PY=36  CONDA_NPY=113

before_install:
- tools/ci/travis/install_miniconda.sh
- conda install conda-build -qy
- conda config --add channels conda-forge

script:
- conda build tools/conda-recipe

after_success:
- pip install coveralls
- coveralls
