language: c
sudo: false

env:
  global:
    - PATH=$HOME/miniconda/bin:$PATH
  matrix:
    - python=2.7  CONDA_PY=27  CONDA_NPY=18
    - python=3.5  CONDA_PY=35  CONDA_NPY=110
    - python=3.6  CONDA_PY=36  CONDA_NPY=111
    - python=3.7  CONDA_PY=37  CONDA_NPY=114

before_install:
- tools/ci/travis/install_miniconda.sh
- conda install conda-build conda-verify -qy
- conda config --add channels conda-forge

script:
- export _PYTHON_SYSCONFIGDATA_NAME='_sysconfigdata_m_linux_x86_64-linux-gnu' 
- conda build tools/conda-recipe

after_script:                                                                                                                                                                                
- bash <(curl -s https://codecov.io/bash) -f $HOME/coverage.xml -e CONDA_PY 
