package:
  name: msmtools
  version: !!str dev

source:
  path: ../..

build:
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython >=0.20
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.8.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]

  run:
    - setuptools
    - numpy
    - scipy
    - six
    - decorator

test:
  source_files:
    - setup.cfg
  requires:
    - pytest
    - pytest-cov

about:
  home: http://github.com/markovmodel/msmtools
  license: LGPLv3+
  summary: "MSMTools"
