package:
  name: msmtools 
  version: !!str dev 

source:
  path: ../.. 

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20
    - numpy >=1.7
    - scipy 
    - nose
    - six
    - decorator
    - nomkl

  run:
    - python
    - setuptools
    - numpy >=1.7
    - scipy
    - six
    - decorator
    - nomkl
test:
  commands:
  # enable the reporting of Python warning
    - pip install pytest-warnings
  source_files:
    - setup.cfg
  requires:
    - pytest 
    - pytest-cov

about:
  home: http://github.com/markovmodel/msmtools
  license: LGPLv3+ 
  summary: "MSMTools"
